// GENERATED by scripts/build-brand-assets.py from public/mascot.svg. Do not edit by hand.
// Original mascot coordinates (viewBox ~ 30 80 310 330 shows the bust + a pose).
export const BUST = `<path d="M108 195 Q100 105 190 96 Q280 105 272 195 L286 282 Q240 296 190 290 Q140 296 94 282 Z" fill="#4a3a78" stroke="#2a2147" stroke-width="3" stroke-linejoin="round"/>

<rect x="172" y="250" width="36" height="46" fill="#ffd9c4" stroke="#2a2147" stroke-width="3"/>
<path d="M96 400 Q100 306 150 286 L230 286 Q280 306 284 400 Z" fill="#6fa8dc" stroke="#2a2147" stroke-width="3" stroke-linejoin="round"/>
<path d="M160 287 L190 335 L220 287 Z" fill="#ffffff" stroke="#2a2147" stroke-width="3" stroke-linejoin="round"/>

<ellipse cx="190" cy="194" rx="70" ry="76" fill="#ffe3d3" stroke="#2a2147" stroke-width="3"/>
<ellipse cx="140" cy="230" rx="14" ry="9" fill="#ff9aa8" opacity="0.65"/>
<ellipse cx="240" cy="230" rx="14" ry="9" fill="#ff9aa8" opacity="0.65"/>

<path d="M145 176 Q160 169 175 175" fill="none" stroke="#2a2147" stroke-width="3" stroke-linecap="round"/>
<path d="M205 175 Q220 169 235 176" fill="none" stroke="#2a2147" stroke-width="3" stroke-linecap="round"/>

<ellipse cx="160" cy="205" rx="13" ry="16" fill="#ffffff"/>
<ellipse cx="220" cy="205" rx="13" ry="16" fill="#ffffff"/>
<ellipse cx="160" cy="208" rx="11" ry="14" fill="#2fa59c"/>
<ellipse cx="220" cy="208" rx="11" ry="14" fill="#2fa59c"/>
<ellipse cx="160" cy="210" rx="6" ry="8" fill="#1d1b3a"/>
<ellipse cx="220" cy="210" rx="6" ry="8" fill="#1d1b3a"/>
<circle cx="155" cy="203" r="4" fill="#ffffff"/>
<circle cx="215" cy="203" r="4" fill="#ffffff"/>
<circle cx="164" cy="214" r="2" fill="#ffffff"/>
<circle cx="224" cy="214" r="2" fill="#ffffff"/>
<path d="M145 200 Q160 188 176 199" fill="none" stroke="#2a2147" stroke-width="3.5" stroke-linecap="round"/>
<path d="M204 199 Q220 188 235 200" fill="none" stroke="#2a2147" stroke-width="3.5" stroke-linecap="round"/>

<circle cx="160" cy="206" r="26" fill="#bfe3ff" fill-opacity="0.25" stroke="#2f3a8c" stroke-width="3"/>
<circle cx="220" cy="206" r="26" fill="#bfe3ff" fill-opacity="0.25" stroke="#2f3a8c" stroke-width="3"/>
<path d="M186 203 Q190 199 194 203" fill="none" stroke="#2f3a8c" stroke-width="3" stroke-linecap="round"/>
<path d="M134 202 L118 198 M246 202 L262 198" fill="none" stroke="#2f3a8c" stroke-width="3" stroke-linecap="round"/>

<path d="M189 228 L191 230" stroke="#c98a73" stroke-width="2.5" stroke-linecap="round"/>
<path d="M178 243 Q190 253 202 243" fill="#e8566b" stroke="#2a2147" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round"/>

<path d="M118 196 Q108 108 190 102 Q272 108 262 196 Q252 154 234 142 Q218 166 190 152 Q162 166 146 142 Q128 154 118 196 Z" fill="#4a3a78" stroke="#2a2147" stroke-width="3" stroke-linejoin="round"/>
<path d="M120 180 Q108 232 122 268 L140 252 Q130 218 138 168 Z" fill="#4a3a78" stroke="#2a2147" stroke-width="3" stroke-linejoin="round"/>
<path d="M260 180 Q272 232 258 268 L240 252 Q250 218 242 168 Z" fill="#4a3a78" stroke="#2a2147" stroke-width="3" stroke-linejoin="round"/>
<path d="M170 112 Q190 122 214 112" fill="none" stroke="#6b58a8" stroke-width="3" stroke-linecap="round"/>

<circle cx="238" cy="124" r="11" fill="#ffd54a" stroke="#2a2147" stroke-width="3"/>
<circle cx="238" cy="124" r="5.5" fill="#e0a92a"/>`

export const POSES = {
  fast: `<path d="M270 356 Q316 322 312 262" fill="none" stroke="#2a2147" stroke-width="26" stroke-linecap="round"/><path d="M270 356 Q316 322 312 262" fill="none" stroke="#6fa8dc" stroke-width="19" stroke-linecap="round"/><circle cx="312" cy="246" r="18" fill="#ffe3d3" stroke="#2a2147" stroke-width="3"/><path d="M80 124 L44 198 H70 L52 262 L102 174 H76 L96 124 Z" fill="#fbd857" stroke="#2a2147" stroke-width="3" stroke-linejoin="round"/>`,
  offline: `<rect x="150" y="316" width="80" height="110" rx="13" fill="#2a2147"/><rect x="158" y="326" width="64" height="88" rx="8" fill="#dfeaff"/><path d="M168 354 Q190 334 212 354" fill="none" stroke="#2a2147" stroke-width="5" stroke-linecap="round"/><path d="M176 367 Q190 355 204 367" fill="none" stroke="#2a2147" stroke-width="5" stroke-linecap="round"/><circle cx="190" cy="381" r="4.5" fill="#2a2147"/><path d="M166 338 L212 396" stroke="#e8566b" stroke-width="7" stroke-linecap="round"/><circle cx="146" cy="376" r="15" fill="#ffe3d3" stroke="#2a2147" stroke-width="3"/><circle cx="234" cy="376" r="15" fill="#ffe3d3" stroke="#2a2147" stroke-width="3"/>`,
  free: `<path d="M112 336 L268 398" fill="none" stroke="#2a2147" stroke-width="28" stroke-linecap="round"/><path d="M112 336 L268 398" fill="none" stroke="#6fa8dc" stroke-width="21" stroke-linecap="round"/><path d="M268 336 L112 398" fill="none" stroke="#2a2147" stroke-width="28" stroke-linecap="round"/><path d="M268 336 L112 398" fill="none" stroke="#6fa8dc" stroke-width="21" stroke-linecap="round"/>`,
} as const

export type Pose = keyof typeof POSES
